bash script.sh introductory.txt 'Introductory.pdf' './Introductory Problems/'
bash script.sh sorting.txt 'Sorting and Searching.pdf' './Sorting and Searching/'
bash script.sh dynamic.txt 'Dynamic Programming.pdf' './Dynamic Programming/'
bash script.sh graph.txt 'Graph Algorithms.pdf' './Graph Algorithms/'
bash script.sh range.txt 'Range Queries.pdf' './Range Queries/'
bash script.sh tree.txt 'Tree Algorithms.pdf' './Tree Algorithms/'
bash script.sh math.txt 'Mathematics.pdf' './Mathematics/'
bash script.sh string.txt 'String Algorithms.pdf' './String Algorithms/'
bash script.sh geometry.txt 'Geometry.pdf' './Geometry/'
bash script.sh advanced.txt 'Advanced Techniques.pdf' './Advanced Techniques/'
bash script.sh sliding.txt 'Sliding Window Problems.pdf' './Sliding Window Problems/'
bash script.sh interactive.txt 'Interactive Problems.pdf' './Interactive Problems/'
bash script.sh bitwise.txt 'Bitwise Operations.pdf' './Bitwise Operations/'
bash script.sh construction.txt 'Construction Problems.pdf' './Construction Problems/'
bash script.sh advanced-graph.txt 'Advanced Graph Problems.pdf' './Advanced Graph Problems/'
bash script.sh counting.txt 'Counting Problems.pdf' './Counting Problems/'
bash script.sh additional.txt 'Additional Problems I.pdf' './Additional Problems I/'
bash script.sh additional-II.txt 'Additional Problems II.pdf' './Additional Problems II/'
