bash better.sh introductory.txt 'Introductory Problems.pdf'
bash better.sh sorting.txt 'Sorting and Searching.pdf'
bash better.sh dynamic.txt 'Dynamic Programming.pdf'
bash better.sh graph.txt 'Graph Algorithms.pdf'
bash better.sh range.txt 'Range Queries.pdf'
bash better.sh tree.txt 'Tree Algorithms.pdf'
bash better.sh math.txt 'Mathematics.pdf'
bash better.sh string.txt 'String Algorithms.pdf'
bash better.sh geometry.txt 'Geometry.pdf'
bash better.sh advanced.txt 'Advanced Techniques.pdf'
bash better.sh sliding.txt 'Sliding Window Problems.pdf'
bash better.sh interactive.txt 'Interactive Problems.pdf'
bash better.sh bitwise.txt 'Bitwise Operations.pdf'
bash better.sh construction.txt 'Construction Problems.pdf'
bash better.sh advanced-graph.txt 'Advanced Graph Problems.pdf'
bash better.sh counting.txt 'Counting Problems.pdf'
bash better.sh additional.txt 'Additional Problems I.pdf'
bash better.sh additional-II.txt 'Additional Problems II.pdf'
