# bash script.sh algebra.html 'Algebra.pdf'
# bash script.sh data_structures.html 'Data Structures.pdf'
# bash script.sh dynamic.html 'Dynamic Programming.pdf'
# bash script.sh string-processing.html 'String Processing.pdf'
# bash script.sh linear-algebra.html 'Linear Algebra.pdf'
# bash script.sh combinatorics.html 'Combinatorics.pdf'
bash script.sh numerical-methods.html 'Numerical Methods.pdf'
bash script.sh geometry.html 'Geometry.pdf'
# bash script.sh graphs.html 'Graphs.pdf'
# bash script.sh misc.html 'Miscellaneous.pdf'
